# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'Fvnction TV' do
  
  project 'Fvnction TV.xcodeproj'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher'
  pod 'XCDYouTubeKit'
  pod "CenteredCollectionView"
  pod "EasyPeasy"
  pod 'AppCenter'
  
end
